name: 测试构建

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: 构建包
      run: python -m build
    - name: 测试构建
      env:
        SESSDATA: "mock_sessdata_for_testing"
      run: |
        python -m pip install dist/*.whl
        python -c "import bilibili_video_info_mcp; import bilibili_video_info_mcp.bilibili_api; import bilibili_video_info_mcp.server"
